#include "lookup.h"
#include "jenkins.h"

std::map<int, const char*> g_TrackGroupMap =
{
    { sumohash("billyhatcher_easy"), "Blizzard Castle" },
    { sumohash("seasidehill_easy"), "Seaside Hill" },
    { sumohash("samba_easy"), "Carnival Town" },
    { sumohash("smb_easy"), "Jumble Jungle" },
    { sumohash("jetsetradio_easy"), "Tokyo-to" },
    { sumohash("houseofthedead_easy"), "Curien Mansion" },
    { sumohash("finalfortress_easy"), "Final Fortress" },
    { sumohash("casinopark_easy"), "Casino Park" },
    { sumohash("billyhatcher_medium"), "Blizzard Castle" },
    { sumohash("seasidehill_medium"), "Seaside Hill" },
    { sumohash("samba_medium"), "Carnival Town" },
    { sumohash("smb_medium"), "Detritus Desert" },
    { sumohash("jetsetradio_medium"), "Tokyo-to" },
    { sumohash("houseofthedead_medium"), "Curien Mansion" },
    { sumohash("finalfortress_medium"), "Final Fortress" },
    { sumohash("casinopark_medium"), "Casino Park" },
    { sumohash("billyhatcher_hard"), "Dino Mountain" },
    { sumohash("seasidehill_hard"), "Seaside Hill" },
    { sumohash("samba_hard"), "Carnival Town" },
    { sumohash("smb_hard"), "Pirates Ocean" },
    { sumohash("jetsetradio_hard"), "Tokyo-to" },
    { sumohash("houseofthedead_hard"), "Curien Mansion" },
    { sumohash("finalfortress_hard"), "Final Fortress" },
    { sumohash("casinopark_hard"), "Casino Park" },
    { sumohash("monkeyball_arena"), "Jumble Jungle" },
    { sumohash("hotd_arena"), "Curien Mansion" },
    { sumohash("seasidehill_arena"), "Seaside Hill" },
};

std::map<int, const char*> g_TrackNameMap =
{
    { sumohash("billyhatcher_easy"), "Icicle Valley" },
    { sumohash("seasidehill_easy"), "Whale Lagoon" },
    { sumohash("samba_easy"), "Sunshine Tour" },
    { sumohash("smb_easy"), "Treetops" },
    { sumohash("jetsetradio_easy"), "Shibuya Downtown" },
    { sumohash("houseofthedead_easy"), "Outer Forest" },
    { sumohash("finalfortress_easy"), "Turbine Loop" },
    { sumohash("casinopark_easy"), "Pinball Highway" },
    { sumohash("billyhatcher_medium"), "Rampart Road" },
    { sumohash("seasidehill_medium"), "Ocean Ruin" },
    { sumohash("samba_medium"), "Jump Parade" },
    { sumohash("smb_medium"), "Sandy Drifts" },
    { sumohash("jetsetradio_medium"), "Rokkaku Hill" },
    { sumohash("houseofthedead_medium"), "Sewer Scrapes" },
    { sumohash("finalfortress_medium"), "Dark Arsenal" },
    { sumohash("casinopark_medium"), "Roulette Road" },
    { sumohash("billyhatcher_hard"), "Lava Lair" },
    { sumohash("seasidehill_hard"), "Lost Palace" },
    { sumohash("samba_hard"), "Rocky-Coaster" },
    { sumohash("smb_hard"), "Monkey Target" },
    { sumohash("jetsetradio_hard"), "Highway Zero" },
    { sumohash("houseofthedead_hard"), "Deadly Route" },
    { sumohash("finalfortress_hard"), "Thunder Deck" },
    { sumohash("casinopark_hard"), "Bingo Party" },
    { sumohash("monkeyball_arena"), "Rumble Ramps" },
    { sumohash("hotd_arena"), "Grave Hard" },
    { sumohash("seasidehill_arena"), "Seaside Square" },
};

std::map<int, MissionInfo> g_MissionInfoMap =
{
    { sumohash("Mission_01"), { "SONIC CRUSH!", "Rival Race"} },
    { sumohash("Mission_02"), { "MARDI GRAS!", "Drift"} },
    { sumohash("Mission_03"), { "FIGHT TO THE FINISH!", "Knockout"} },
    { sumohash("Mission_04"), { "TREASURE ISLAND!", "Collect"} },
    { sumohash("Mission_05"), { "WHITE KNUCKLE RIDE!", "Race"} },
    { sumohash("Mission_06"), { "HEDGEHOG TARGET PRACTICE!", "Hit Contest"} },
    { sumohash("Mission_07"), { "GRAFFITI SPEED STAR!", "Boost"} },
    { sumohash("Mission_08"), { "SEASIDE CUP", "Grand Prix"} },
    { sumohash("Mission_09"), { "EGG-STREMELY SIMPLE!", "Time Gates"} },
    { sumohash("Mission_10"), { "RACE YOUR BETS!", "Race"} },
    { sumohash("Mission_11"), { "JET SET SLIDE!", "Drift"} },
    { sumohash("Mission_12"), { "EGG-CITING TIMES!", "Hit Contest"} },
    { sumohash("Mission_13"), { "EMERALD SNATCHER!", "Collect"} },
    { sumohash("Mission_14"), { "BEAT THE DEALER!", "Rival Race"} },
    { sumohash("Mission_15"), { "FIESTA FOOD DODGE!", "Avoid"} },
    { sumohash("Mission_16"), { "BLIZZARD CUP", "Grand Prix"} },
    { sumohash("Mission_17"), { "FIESTA CLEAN-UP CREW!", "Hit Contest"} },
    { sumohash("Mission_18"), { "JET SET RACE!", "Knockout"} },
    { sumohash("Mission_19"), { "NITRO NIGHTS!", "Boost"} },
    { sumohash("Mission_20"), { "SEAFOOD DINNER!", "Hit Contest"} },
    { sumohash("Mission_21"), { "EGG-CEPTIONAL!", "Race"} },
    { sumohash("Mission_22"), { "MONKEY CAPSULES, I LOVE 'EM!", "Time Gates"} },
    { sumohash("Mission_23"), { "SKY PIRATE!", "Battle Race"} },
    { sumohash("Mission_24"), { "TOKYO-TO CUP", "Grand Prix"} },
    { sumohash("Mission_25"), { "EGG-STRAORDINARY!", "Battle Race"} },
    { sumohash("Mission_26"), { "SPOOKY SPEEDWAY!", "Drift"} },
    { sumohash("Mission_27"), { "MARACA MADNESS!", "Knockout"} },
    { sumohash("Mission_28"), { "BANANA BONUS!", "Collect"} },
    { sumohash("Mission_29"), { "WATER SLIDE!", "Time Gates"} },
    { sumohash("Mission_30"), { "FARE GAME!", "Rival Race"} },
    { sumohash("Mission_31"), { "CHU CHU AVENUE!", "Hit Contest"} },
    { sumohash("Mission_32"), { "CARNIVAL CUP", "Grand Prix"} },
    { sumohash("Mission_33"), { "BIG BANKER PAYOUT!", "Collect"} },
    { sumohash("Mission_34"), { "CREEPY CRAWLIES!", "Knockout"} },
    { sumohash("Mission_35"), { "FORTRESS FIASCO!", "Boost"} },
    { sumohash("Mission_36"), { "HIDDEN RING STASH!", "Collect"} },
    { sumohash("Mission_37"), { "TO DRIFT OR NOT TO DRIFT?", "Time Gates"} },
    { sumohash("Mission_38"), { "MONKEY MUDDLE!", "Race"} },
    { sumohash("Mission_39"), { "DRIFT FROM A ROSE!", "Drift"} },
    { sumohash("Mission_40"), { "CASINO CUP", "Grand Prix"} },
    { sumohash("Mission_41"), { "THINGS GO BUMP IN THE NIGHT!", "Battle Race"} },
    { sumohash("Mission_42"), { "MONKEY TROUBLE!", "Score Gates"} },
    { sumohash("Mission_43"), { "EGG-SPLOSIVE SLIDE!", "Drift"} },
    { sumohash("Mission_44"), { "TAILSPIN!", "Race"} },
    { sumohash("Mission_45"), { "TOKYO-TO SHOW!", "Time Gates"} },
    { sumohash("Mission_46"), { "HAVE YOU SEEN LAN DI?", "Knockout"} },
    { sumohash("Mission_47"), { "FACTORY FROLICS!", "Rival Race"} },
    { sumohash("Mission_48"), { "HORRIBLE CUP", "Grand Prix"} },
    { sumohash("Mission_49"), { "GOING BANANAS!", "Drift"} },
    { sumohash("Mission_50"), { "SPACE CHANNEL DRIVE!", "Battle Race"} },
    { sumohash("Mission_51"), { "HAUNTED HOEDOWN!", "Hit Contest"} },
    { sumohash("Mission_52"), { "BONANZA BLAST!", "Race"} },
    { sumohash("Mission_53"), { "FACTORY CRASH!", "Time Gates"} },
    { sumohash("Mission_54"), { "HOUSE OF THE DREAD!", "Knockout"} },
    { sumohash("Mission_55"), { "SLIP SLIDE!", "Drift"} },
    { sumohash("Mission_56"), { "SUPER MONKEY CUP", "Grand Prix"} },
    { sumohash("Mission_57"), { "LETHAL LAVA!", "Knockout"} },
    { sumohash("Mission_58"), { "FINAL COUNTDOWN!", "Collect"} },
    { sumohash("Mission_59"), { "SUPER MONKEY'S ALL!", "Rival Race"} },
    { sumohash("Mission_60"), { "GRAFFITI DASH!", "Boost"} },
    { sumohash("Mission_61"), { "BEACH PARTY!", "Battle Race"} },
    { sumohash("Mission_62"), { "EVERY SECOND COUNTS!", "Time Gates"} },
    { sumohash("Mission_63"), { "ROBOT CUP", "Grand Prix"} },
    { sumohash("Mission_64"), { "SAVE THE DAY SONIC!!", "Hit Contest"} },
};